// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nghuyentrangvt98/banhmioi/ent/product"
)

// ProductCreate is the builder for creating a Product entity.
type ProductCreate struct {
	config
	mutation *ProductMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *ProductCreate) SetName(s string) *ProductCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetDescription sets the "description" field.
func (pc *ProductCreate) SetDescription(s string) *ProductCreate {
	pc.mutation.SetDescription(s)
	return pc
}

// SetListPrice sets the "list_price" field.
func (pc *ProductCreate) SetListPrice(i int64) *ProductCreate {
	pc.mutation.SetListPrice(i)
	return pc
}

// SetSalePrice sets the "sale_price" field.
func (pc *ProductCreate) SetSalePrice(i int64) *ProductCreate {
	pc.mutation.SetSalePrice(i)
	return pc
}

// SetVariation sets the "variation" field.
func (pc *ProductCreate) SetVariation(m map[string]interface{}) *ProductCreate {
	pc.mutation.SetVariation(m)
	return pc
}

// SetStockQty sets the "stock_qty" field.
func (pc *ProductCreate) SetStockQty(i int32) *ProductCreate {
	pc.mutation.SetStockQty(i)
	return pc
}

// SetProductURL sets the "product_url" field.
func (pc *ProductCreate) SetProductURL(s string) *ProductCreate {
	pc.mutation.SetProductURL(s)
	return pc
}

// SetCategory sets the "category" field.
func (pc *ProductCreate) SetCategory(s string) *ProductCreate {
	pc.mutation.SetCategory(s)
	return pc
}

// SetMeasurementUnit sets the "measurement_unit" field.
func (pc *ProductCreate) SetMeasurementUnit(s string) *ProductCreate {
	pc.mutation.SetMeasurementUnit(s)
	return pc
}

// SetID sets the "id" field.
func (pc *ProductCreate) SetID(i int) *ProductCreate {
	pc.mutation.SetID(i)
	return pc
}

// Mutation returns the ProductMutation object of the builder.
func (pc *ProductCreate) Mutation() *ProductMutation {
	return pc.mutation
}

// Save creates the Product in the database.
func (pc *ProductCreate) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProductCreate) SaveX(ctx context.Context) *Product {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ProductCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ProductCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProductCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Product.name"`)}
	}
	if _, ok := pc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Product.description"`)}
	}
	if _, ok := pc.mutation.ListPrice(); !ok {
		return &ValidationError{Name: "list_price", err: errors.New(`ent: missing required field "Product.list_price"`)}
	}
	if _, ok := pc.mutation.SalePrice(); !ok {
		return &ValidationError{Name: "sale_price", err: errors.New(`ent: missing required field "Product.sale_price"`)}
	}
	if _, ok := pc.mutation.Variation(); !ok {
		return &ValidationError{Name: "variation", err: errors.New(`ent: missing required field "Product.variation"`)}
	}
	if _, ok := pc.mutation.StockQty(); !ok {
		return &ValidationError{Name: "stock_qty", err: errors.New(`ent: missing required field "Product.stock_qty"`)}
	}
	if _, ok := pc.mutation.ProductURL(); !ok {
		return &ValidationError{Name: "product_url", err: errors.New(`ent: missing required field "Product.product_url"`)}
	}
	if _, ok := pc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Product.category"`)}
	}
	if _, ok := pc.mutation.MeasurementUnit(); !ok {
		return &ValidationError{Name: "measurement_unit", err: errors.New(`ent: missing required field "Product.measurement_unit"`)}
	}
	return nil
}

func (pc *ProductCreate) sqlSave(ctx context.Context) (*Product, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *ProductCreate) createSpec() (*Product, *sqlgraph.CreateSpec) {
	var (
		_node = &Product{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(product.Table, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := pc.mutation.ListPrice(); ok {
		_spec.SetField(product.FieldListPrice, field.TypeInt64, value)
		_node.ListPrice = value
	}
	if value, ok := pc.mutation.SalePrice(); ok {
		_spec.SetField(product.FieldSalePrice, field.TypeInt64, value)
		_node.SalePrice = value
	}
	if value, ok := pc.mutation.Variation(); ok {
		_spec.SetField(product.FieldVariation, field.TypeJSON, value)
		_node.Variation = value
	}
	if value, ok := pc.mutation.StockQty(); ok {
		_spec.SetField(product.FieldStockQty, field.TypeInt32, value)
		_node.StockQty = value
	}
	if value, ok := pc.mutation.ProductURL(); ok {
		_spec.SetField(product.FieldProductURL, field.TypeString, value)
		_node.ProductURL = value
	}
	if value, ok := pc.mutation.Category(); ok {
		_spec.SetField(product.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := pc.mutation.MeasurementUnit(); ok {
		_spec.SetField(product.FieldMeasurementUnit, field.TypeString, value)
		_node.MeasurementUnit = value
	}
	return _node, _spec
}

// ProductCreateBulk is the builder for creating many Product entities in bulk.
type ProductCreateBulk struct {
	config
	builders []*ProductCreate
}

// Save creates the Product entities in the database.
func (pcb *ProductCreateBulk) Save(ctx context.Context) ([]*Product, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Product, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProductCreateBulk) SaveX(ctx context.Context) []*Product {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ProductCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ProductCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
