// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nghuyentrangvt98/banhmioi/ent/predicate"
	"github.com/nghuyentrangvt98/banhmioi/ent/product"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (pu *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *ProductUpdate) SetName(s string) *ProductUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetDescription sets the "description" field.
func (pu *ProductUpdate) SetDescription(s string) *ProductUpdate {
	pu.mutation.SetDescription(s)
	return pu
}

// SetListPrice sets the "list_price" field.
func (pu *ProductUpdate) SetListPrice(i int64) *ProductUpdate {
	pu.mutation.ResetListPrice()
	pu.mutation.SetListPrice(i)
	return pu
}

// AddListPrice adds i to the "list_price" field.
func (pu *ProductUpdate) AddListPrice(i int64) *ProductUpdate {
	pu.mutation.AddListPrice(i)
	return pu
}

// SetSalePrice sets the "sale_price" field.
func (pu *ProductUpdate) SetSalePrice(i int64) *ProductUpdate {
	pu.mutation.ResetSalePrice()
	pu.mutation.SetSalePrice(i)
	return pu
}

// AddSalePrice adds i to the "sale_price" field.
func (pu *ProductUpdate) AddSalePrice(i int64) *ProductUpdate {
	pu.mutation.AddSalePrice(i)
	return pu
}

// SetVariation sets the "variation" field.
func (pu *ProductUpdate) SetVariation(m map[string]interface{}) *ProductUpdate {
	pu.mutation.SetVariation(m)
	return pu
}

// SetStockQty sets the "stock_qty" field.
func (pu *ProductUpdate) SetStockQty(i int32) *ProductUpdate {
	pu.mutation.ResetStockQty()
	pu.mutation.SetStockQty(i)
	return pu
}

// AddStockQty adds i to the "stock_qty" field.
func (pu *ProductUpdate) AddStockQty(i int32) *ProductUpdate {
	pu.mutation.AddStockQty(i)
	return pu
}

// SetProductURL sets the "product_url" field.
func (pu *ProductUpdate) SetProductURL(s string) *ProductUpdate {
	pu.mutation.SetProductURL(s)
	return pu
}

// SetCategory sets the "category" field.
func (pu *ProductUpdate) SetCategory(s string) *ProductUpdate {
	pu.mutation.SetCategory(s)
	return pu
}

// SetMeasurementUnit sets the "measurement_unit" field.
func (pu *ProductUpdate) SetMeasurementUnit(s string) *ProductUpdate {
	pu.mutation.SetMeasurementUnit(s)
	return pu
}

// Mutation returns the ProductMutation object of the builder.
func (pu *ProductUpdate) Mutation() *ProductMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProductUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProductUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *ProductUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
	}
	if value, ok := pu.mutation.ListPrice(); ok {
		_spec.SetField(product.FieldListPrice, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedListPrice(); ok {
		_spec.AddField(product.FieldListPrice, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.SalePrice(); ok {
		_spec.SetField(product.FieldSalePrice, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedSalePrice(); ok {
		_spec.AddField(product.FieldSalePrice, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.Variation(); ok {
		_spec.SetField(product.FieldVariation, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.StockQty(); ok {
		_spec.SetField(product.FieldStockQty, field.TypeInt32, value)
	}
	if value, ok := pu.mutation.AddedStockQty(); ok {
		_spec.AddField(product.FieldStockQty, field.TypeInt32, value)
	}
	if value, ok := pu.mutation.ProductURL(); ok {
		_spec.SetField(product.FieldProductURL, field.TypeString, value)
	}
	if value, ok := pu.mutation.Category(); ok {
		_spec.SetField(product.FieldCategory, field.TypeString, value)
	}
	if value, ok := pu.mutation.MeasurementUnit(); ok {
		_spec.SetField(product.FieldMeasurementUnit, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductMutation
}

// SetName sets the "name" field.
func (puo *ProductUpdateOne) SetName(s string) *ProductUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetDescription sets the "description" field.
func (puo *ProductUpdateOne) SetDescription(s string) *ProductUpdateOne {
	puo.mutation.SetDescription(s)
	return puo
}

// SetListPrice sets the "list_price" field.
func (puo *ProductUpdateOne) SetListPrice(i int64) *ProductUpdateOne {
	puo.mutation.ResetListPrice()
	puo.mutation.SetListPrice(i)
	return puo
}

// AddListPrice adds i to the "list_price" field.
func (puo *ProductUpdateOne) AddListPrice(i int64) *ProductUpdateOne {
	puo.mutation.AddListPrice(i)
	return puo
}

// SetSalePrice sets the "sale_price" field.
func (puo *ProductUpdateOne) SetSalePrice(i int64) *ProductUpdateOne {
	puo.mutation.ResetSalePrice()
	puo.mutation.SetSalePrice(i)
	return puo
}

// AddSalePrice adds i to the "sale_price" field.
func (puo *ProductUpdateOne) AddSalePrice(i int64) *ProductUpdateOne {
	puo.mutation.AddSalePrice(i)
	return puo
}

// SetVariation sets the "variation" field.
func (puo *ProductUpdateOne) SetVariation(m map[string]interface{}) *ProductUpdateOne {
	puo.mutation.SetVariation(m)
	return puo
}

// SetStockQty sets the "stock_qty" field.
func (puo *ProductUpdateOne) SetStockQty(i int32) *ProductUpdateOne {
	puo.mutation.ResetStockQty()
	puo.mutation.SetStockQty(i)
	return puo
}

// AddStockQty adds i to the "stock_qty" field.
func (puo *ProductUpdateOne) AddStockQty(i int32) *ProductUpdateOne {
	puo.mutation.AddStockQty(i)
	return puo
}

// SetProductURL sets the "product_url" field.
func (puo *ProductUpdateOne) SetProductURL(s string) *ProductUpdateOne {
	puo.mutation.SetProductURL(s)
	return puo
}

// SetCategory sets the "category" field.
func (puo *ProductUpdateOne) SetCategory(s string) *ProductUpdateOne {
	puo.mutation.SetCategory(s)
	return puo
}

// SetMeasurementUnit sets the "measurement_unit" field.
func (puo *ProductUpdateOne) SetMeasurementUnit(s string) *ProductUpdateOne {
	puo.mutation.SetMeasurementUnit(s)
	return puo
}

// Mutation returns the ProductMutation object of the builder.
func (puo *ProductUpdateOne) Mutation() *ProductMutation {
	return puo.mutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (puo *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Product entity.
func (puo *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
	}
	if value, ok := puo.mutation.ListPrice(); ok {
		_spec.SetField(product.FieldListPrice, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedListPrice(); ok {
		_spec.AddField(product.FieldListPrice, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.SalePrice(); ok {
		_spec.SetField(product.FieldSalePrice, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedSalePrice(); ok {
		_spec.AddField(product.FieldSalePrice, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.Variation(); ok {
		_spec.SetField(product.FieldVariation, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.StockQty(); ok {
		_spec.SetField(product.FieldStockQty, field.TypeInt32, value)
	}
	if value, ok := puo.mutation.AddedStockQty(); ok {
		_spec.AddField(product.FieldStockQty, field.TypeInt32, value)
	}
	if value, ok := puo.mutation.ProductURL(); ok {
		_spec.SetField(product.FieldProductURL, field.TypeString, value)
	}
	if value, ok := puo.mutation.Category(); ok {
		_spec.SetField(product.FieldCategory, field.TypeString, value)
	}
	if value, ok := puo.mutation.MeasurementUnit(); ok {
		_spec.SetField(product.FieldMeasurementUnit, field.TypeString, value)
	}
	_node = &Product{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
